### ISSUE TITLE
implement v1 endpoints

### ISSUE THREAD

**Issue by fczuardi** [calamar-io/controltower-api#3]
- [x] ```/v1/customers``` POST (#4)
- [x] ```/v1/customers/{ customerId }``` GET (#5)
- [x] ```/v1/customers/{ customerId }``` PUT (#6)
- [x] ```/v1/bots``` POST (#7)
- [x] ```/v1/bots/{ botId }``` GET (#8)
- [x] ```/v1/bots/{ botId }``` PUT (#9)
- [x] ```/v1/users``` POST (#10)
- [x] ```/v1/users/{ userId }``` GET (#11)
- [x] ```/v1/users/{ userId }``` PUT (#12)

**Comment by fczuardi** [comment]
it would be nice to have tests for those endpoints
